spring:
  application:
    name: shppingmall
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{your-url}:{your-port}/{your-database}?useSSL=false&allowPulbicKeyRestrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: {your-username}
    password: {your-password}
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: true
    enabled: true
    prefix: classpath:/templates/
